# -*- coding: utf-8 -*-
import gitlab
import pandas as pd
import Bert
# Form implementation generated from reading ui file 'bishe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
import main
import commit_get_test
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 450, 161, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 560, 161, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 290, 111, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 120, 421, 121))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(360, 290, 281, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 490, 161, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 370, 141, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 370, 281, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 330, 91, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 330, 281, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 527, 161, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 410, 391, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 490, 281, 20))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton.clicked.connect(lambda:self.CSV()) # type: ignore
        self.pushButton_3.clicked.connect(lambda: self.ask_GPT4()) # type: ignore
        self.pushButton_4.clicked.connect(lambda :self.Bert()) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def CSV(self):
        commit_get_test.ACCESS_TOKEN = self.lineEdit.text()
        commit_get_test.REPO_ID = self.lineEdit_3.text()
        commit_get_test.getcommits()
    def ask_GPT4(self):
        print("1")
        main.openai.api_key=self.lineEdit_2.text()
        print("2")
        data = pd.read_csv('gitlab_commits.csv')

        texts = data['Message'] + "" + data['Author Name']
        print("1")

        print(texts)
        prompt = "Read the data and analyse what work each person did, the data is as follows：" + texts.str.cat(sep='\n')
        system_intel = " answer my questions as if you were an expert in the field."
        main.ask_GPT4(system_intel, prompt)
    def Bert(self):
        Bert.grouped_data = []

        number = self.lineEdit_4.text()
        k = int(number)

        print(k)
        Bert.Bert(k)
        Bert.openai.api_key = ""
            #self.lineEdit_2.text()
        data_json = str(Bert.grouped_data)
        prompt = "This is a cluster of gitlab submissions after clustering, each cluster means a function and I need you to carefully analyze the number of clusters and then what did everyone do in each cluster:" + data_json
        Bert.Bert_askGpt4(k)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p align=\"right\"><a href=\"https://github.com/Liuliusui/Gitlab-Commits-Analysis/blob/main/README.md\"><span style=\" text-decoration: underline; color:#0000ff;\">Private Token</span></a></p></body></html>"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Gitlab Commits Analysis</span></p><p><br/></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "GPT Analysis"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Open.api_key</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Project ID"))
        self.pushButton_4.setText(_translate("MainWindow", "Bert+GPT Analysis"))
        self.lineEdit_4.setText(_translate("MainWindow", "Change the number of clusters here.Default to 4"))
        self.label_6.setText(_translate("MainWindow", "Suitable for small amounts of data："))


if __name__ == '__main__':

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_MainWindow()  # 创建PyQt设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt窗体的方法对窗体对象进行初始化设置
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程
